(executables
 (names
  alternating
  mod3
  div7
  alternating_socket
  traffic
  vending
  suffix
  socket_learn
  socket_teach
  traffic_socket
  vending_socket
  suffix_socket
  keylock_diag)
 (public_names
  dfa.alternating
  dfa.mod3
  dfa.div7
  dfa.alternating_socket
  moore.traffic
  mealy.vending
  nfa.suffix
  dfa.socket_learn
  dfa.socket_teach
  moore.traffic_socket
  mealy.vending_socket
  nfa.suffix_socket
  dfa.keylock_diag)
 (libraries lstar unix threads str)
 (flags
  (:standard -w -26))
 (package lstar))
